apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: fixable-severity-at-least-important
  namespace: rhacs
spec:
  name: Fixable Severity at least Important
  description: Alert on deployments with fixable vulnerabilities with a Severity Rating
    at least Important
  rationale: Known vulnerabilities make it easier for adversaries to exploit your
    application. You can fix these high-severity vulnerabilities by updating to a
    newer version of the affected component(s).
  remediation: Use your package manager to update to a fixed version in future builds
    or speak with your security team to mitigate the vulnerabilities.
  categories:
  - Parasol Secured Build Gate
  lifecycleStages:
  - BUILD
  severity: HIGH_SEVERITY
  enforcementActions:
  - FAIL_BUILD_ENFORCEMENT
  disabled: false
  policyVersion: '1.1'
  policySections:
  - sectionName: ''
    policyGroups:
    - fieldName: Fixed By
      booleanOperator: OR
      negate: false
      values:
      - value: .*
    - fieldName: Severity
      booleanOperator: OR
      negate: false
      values:
      - value: '>= IMPORTANT'
